name: iosApp
options:
  bundleIdPrefix: com.chaijie.app
  deploymentTarget:
    iOS: "14.1"
  xcodeVersion: "16.2"

settings:
  base:
    SWIFT_VERSION: "5.0"
    SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/iosApp-Bridging-Header.h"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.chaijie.app
        PRODUCT_NAME: iosApp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CLANG_ENABLE_OBJC_ARC: YES
    dependencies:
      - framework: Photos.framework
    postBuildScripts: []
